// This is an independent project of an individual developer. Dear PVS-Studio, please check it.
// PVS-Studio Static Code Analyzer for C, C++, C#, and Java: http://www.viva64.com
// Global using directives

global using CommunityToolkit.Mvvm.Input;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using System;
global using System.Collections.Generic;
global using System.Collections.ObjectModel;
global using System.ComponentModel;
global using System.Diagnostics;
global using System.Drawing;
global using System.Globalization;
global using System.IO;
global using System.Linq;
global using System.Reflection;
global using System.Threading;
global using System.Threading.Tasks;
global using System.Windows;
global using System.Windows.Controls;
global using System.Windows.Data;
global using System.Windows.Threading;
global using LiveCharts;
global using LiveCharts.Configurations;
global using LiveCharts.Defaults;
global using LiveCharts.Wpf;
global using TgDownloader.Helpers;
global using TgDownloader.Models;
global using TgDownloaderWinDesktop.Common;
global using TgDownloaderWinDesktop.Helpers;
global using TgDownloaderWinDesktop.Models;
global using TgDownloaderWinDesktop.Services;
global using TgDownloaderWinDesktop.Utils;
global using TgDownloaderWinDesktop.ViewModels;
global using TgDownloaderWinDesktop.Views;
global using TgDownloaderWinDesktop.Views.Pages;
global using TgLocalization.Helpers;
global using TgStorage;
global using TgStorage.Common;
global using TgStorage.Domain.Apps;
global using TgStorage.Helpers;
global using TgStorage.Domain.Proxies;
global using TgStorage.Domain.Sources;
global using TgStorage.Models;
global using TgStorage.Utils;
global using Wpf.Ui.Common;
global using Wpf.Ui.Common.Interfaces;
global using Wpf.Ui.Controls;
global using Wpf.Ui.Controls.Interfaces;
global using Wpf.Ui.Mvvm.Contracts;
global using Wpf.Ui.Mvvm.Services;
global using Clipboard = Wpf.Ui.Common.Clipboard;
global using MenuItem = Wpf.Ui.Controls.MenuItem;
global using TgDesktopUtils = TgDownloaderWinDesktop.Utils.TgDesktopUtils;
global using TgMvvmAppModel = TgStorage.Domain.Apps.TgXpoAppViewModel;