// This is an independent project of an individual developer. Dear PVS-Studio, please check it.
// PVS-Studio Static Code Analyzer for C, C++, C#, and Java: http://www.viva64.com

global using Clipboard = Wpf.Ui.Common.Clipboard;
global using CommunityToolkit.Mvvm.Input;
global using LiveCharts.Wpf;
global using LiveCharts;
global using MenuItem = Wpf.Ui.Controls.MenuItem;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using System.Collections.Generic;
global using System.Collections.ObjectModel;
global using System.Diagnostics;
global using System.Drawing;
global using System.Globalization;
global using System.IO;
global using System.Linq;
global using System.Reflection;
global using System.Threading.Tasks;
global using System.Threading;
global using System.Windows.Controls;
global using System.Windows.Data;
global using System.Windows.Threading;
global using System.Windows;
global using System;
global using TgDesktopUtils = TgDownloaderWinDesktopWPF.Utils.TgDesktopUtils;
global using TgDownloader.Helpers;
global using TgDownloaderWinDesktopWPF.Common;
global using TgDownloaderWinDesktopWPF.Models;
global using TgDownloaderWinDesktopWPF.Services;
global using TgDownloaderWinDesktopWPF.ViewModels;
global using TgDownloaderWinDesktopWPF.Views.Pages;
global using TgDownloaderWinDesktopWPF.Views;
global using TgInfrastructure.Helpers;
global using TgStorage.Common;
global using TgStorage.Domain.Apps;
global using TgStorage.Domain.Proxies;
global using TgStorage.Domain.Sources;
global using TgStorage.Enums;
global using TgStorage.Helpers;
global using TgStorage.Models;
global using TgStorage.Utils;
global using TgStorage;
global using Wpf.Ui.Common.Interfaces;
global using Wpf.Ui.Common;
global using Wpf.Ui.Controls.Interfaces;
global using Wpf.Ui.Controls;
global using Wpf.Ui.Mvvm.Contracts;
global using Wpf.Ui.Mvvm.Services;
